### PR TITLE
Provide specific client

### PR DESCRIPTION
**Pull request by adrian-goe**

### CODE REVIEW

**Comment by geisterfurz007** [comment]
What do we need this for?

**Comment by adrian-goe** [comment]
Since we use node alpine in our docker image to reduce image size, we need the linux-musl build. The other one are just to support all sorts of platforms. Since I don't know witch platforms other developers use for dev, I thought to add them

**Comment by geisterfurz007** [comment]
I might be wrong but through the way the package is currently used (in YesBot at least), the package isn't distributed including its sources. Instead depending projects are responsible for generating sources postinstall. As native is the default (see [Docs](https://www.prisma.io/docs/concepts/components/prisma-schema/generators#the-native-binary-target)), this means, that the binary is picked based on the generating operating system. When building in an alpine container, it should pick linux-musl by default, when building on a Mac, it should pick darwin. If we don't plan on distributing the package including the binaries, I don't think this does anything but increase the generated output.

**Comment by adrian-goe** [comment]
we do not build in alpine, we build in native Ubuntu 🙈  we use it in an alpine client and with postinstall we need this.

**Review by geisterfurz007 — APPROVED** [review]

**Pull request merged**
